Lf 19
RicardoTaverna/listafacil pull request #26
Opened 2021-05-04 03:45 UTC by RicardoTaverna

2021-05-04 03:45 UTC, RicardoTaverna commented
![](https://github.trello.services/images/mini-trello-icon.png) [LF-19 - Corrigir chamada da API menorpreco](https://trello.com/c/cLbfuzum/28-lf-19-corrigir-chamada-da-api-menorpreco)

2021-05-05 00:29 UTC, stengrat requested changes

2021-05-05 00:29 UTC, stengrat commented on backend/app/Controllers/Http/ProductController.js
> +   	 * @param {auth} ctx.auth
```suggestion
	 * @param {auth} ctx.auth
```

2021-05-05 00:31 UTC, stengrat approved these changes

2021-05-05 00:31 UTC, merged